### ISSUE TITLE
Trouble Running Tests

### ISSUE THREAD

**Issue by MisterJimson** [supabase-community/gotrue-csharp#22]
Hello!

Trying to run the tests in the repo.

`dotnet test` returns the error below for most tests.

It looks like the tests try to hit `http://localhost:9999`. Is there something that should be spun up first?

```
 Error Message:
   Test method GotrueTests.Client.ClientListUsers threw exception: 
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
  Stack Trace:
      at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Supabase.Gotrue.Helpers.MakeRequest(HttpMethod method, String url, Object data, Dictionary`2 headers) in /Users/jrai/git/gotrue-csharp/Gotrue/Helpers.cs:line 90
   at Supabase.Gotrue.Helpers.MakeRequest[T](HttpMethod method, String url, Object data, Dictionary`2 headers) in /Users/jrai/git/gotrue-csharp/Gotrue/Helpers.cs:line 44
   at Supabase.Gotrue.Client.ListUsers(String jwt, String filter, String sortBy, SortOrder sortOrder, Nullable`1 page, Nullable`1 perPage) in /Users/jrai/git/gotrue-csharp/Gotrue/Client.cs:line 499
   at GotrueTests.Client.ClientListUsers() in /Users/jrai/git/gotrue-csharp/GotrueTests/Client.cs:line 263
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

**Comment by acupofjose** [comment]
Sorry I’m away from my computer this weekend - so mobile only for now!

Yes indeed - you’ll need to have `docker` and `docker-compose` installed then do a `docker-compose up -d` in the root of the repo to spin up the testing servers.
